=== DanielPettersson/solstrale-json/schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://github.com/DanielPettersson/solstrale-json/schema.json",
    "title": "Solstrale JSON",
    "description": "A schema for describing a solstrale scene",
    "type": "object",

    "properties": {
        "world": {
            "$ref": "#/$defs/hittable"
        },
        "camera": {
            "type": "object"
        },
        "background": {
            "type": "object"
        },
        "renderConfig": {
            "type": "object"
        }
    },

    "required": ["world", "camera", "background", "renderConfig"],

    "$defs": {
        "hittable": {
            "type": "object"
        }
    }
}

=== DanielPettersson/solstrale-json/tests/translation-with-non-existing-image-path.json
{
    "world": {
        "type": "translation",
        "object": {
            "type": "sphere",
            "center": {"x": 1, "y": 1, "z": 1},
            "radius": 1,
            "mat": {
                "type": "lambertian",
                "texture": {
                    "type": "image",
                    "path": "",
                    "mirror": false
                }
            }
        },
        "offset": {"x": 1, "y": 1, "z": 1}
    },
    "camera": {
        "imageWidth": 1,
        "imageHeight": 1,
        "verticalFovDegrees": 1,
        "apertureSize": 1,
        "focusDistance": 1,
        "lookFrom": {"x": 1, "y": 1, "z": 1},
        "lookAt": {"x": 1, "y": 1, "z": 1},
        "vup": {"x": 1, "y": 1, "z": 1}
    },
    "background": {"r": 1, "g": 1, "b": 1},
    "renderConfig": {
        "imageWidth": 1,
        "imageHeight": 2,
        "samplesPerPixel": 3,
        "shader": {
            "type": "albedo"
        },
        "postProcessor": null
    }
    
}

=== DanielPettersson/solstrale-json/tests/hittables.json
{
    "world": {
        "type": "hittableList",
        "list": [
            {
                "type": "constantMedium",
                "object": {
                    "type": "sphere",
                    "center": {"x": 1, "y": 1, "z": 1},
                    "radius": 1,
                    "mat": {
                        "type": "lambertian",
                        "texture": {
                            "type": "solidColor",
                            "color": {"r": 1, "g": 1, "b": 1}
                        }
                    }
                },
                "density": 1,
                "texture": {
                    "type": "solidColor",
                    "color": {"r": 1, "g": 1, "b": 1}
                }
                
            },
            {
                "type": "motionBlur",
                "object": {
                    "type": "sphere",
                    "center": {"x": 1, "y": 1, "z": 1},
                    "radius": 1,
                    "mat": {
                        "type": "lambertian",
                        "texture": {
                            "type": "solidColor",
                            "color": {"r": 1, "g": 1, "b": 1}
                        }
                    }
                },
                "blurDirection": {"x": 1, "y": 1, "z": 1}                
            },
            {
                "type": "rotationY",
                "object": {
                    "type": "sphere",
                    "center": {"x": 1, "y": 1, "z": 1},
                    "radius": 1,
                    "mat": {
                        "type": "lambertian",
                        "texture": {
                            "type": "solidColor",
                            "color": {"r": 1, "g": 1, "b": 1}
                        }
                    }
                },
                "angle": 1
            },
            {
                "type": "translation",
                "object": {
                    "type": "sphere",
                    "center": {"x": 1, "y": 1, "z": 1},
                    "radius": 1,
                    "mat": {
                        "type": "lambertian",
                        "texture": {
                            "type": "solidColor",
                            "color": {"r": 1, "g": 1, "b": 1}
                        }
                    }
                },
                "offset": {"x": 1, "y": 1, "z": 1}
            },
            {
                "type": "sphere",
                "center": {"x": 1, "y": 1, "z": 1},
                "radius": 1,
                "mat": {
                    "type": "lambertian",
                    "texture": {
                        "type": "solidColor",
                        "color": {"r": 1, "g": 1, "b": 1}
                    }
                }
            },
            {
                "type": "quad",
                "corner": {"x": 1, "y": 1, "z": 1},
                "dirU": {"x": 1, "y": 1, "z": 1},
                "dirV": {"x": 1, "y": 1, "z": 1},
                "mat": {
                    "type": "lambertian",
                    "texture": {
                        "type": "solidColor",
                        "color": {"r": 1, "g": 1, "b": 1}
                    }
                }
            }
        ]
    },
    "camera": {
        "imageWidth": 1,
        "imageHeight": 1,
        "verticalFovDegrees": 1,
        "apertureSize": 1,
        "focusDistance": 1,
        "lookFrom": {"x": 1, "y": 1, "z": 1},
        "lookAt": {"x": 1, "y": 1, "z": 1},
        "vup": {"x": 1, "y": 1, "z": 1}
    },
    "background": {"r": 1, "g": 1, "b": 1},
    "renderConfig": {
        "imageWidth": 1,
        "imageHeight": 2,
        "samplesPerPixel": 3,
        "shader": {
            "type": "albedo"
        },
        "postProcessor": null
    }
    
}

=== DanielPettersson/solstrale-json/tests/renderConfig-missing-shader.json
{
    "world": {
        "type": "sphere",
        "center": {"x": 1, "y": 1, "z": 1},
        "radius": 1,
        "mat": {
            "type": "lambertian",
            "texture": {
                "type": "solidColor",
                "color": {"x": 1, "y": 1, "z": 1}
            }
        }
    },
    "camera": {
        "imageWidth": 1,
        "imageHeight": 1,
        "verticalFovDegrees": 1,
        "apertureSize": 1,
        "focusDistance": 1,
        "lookFrom": {"x": 1, "y": 1, "z": 1},
        "lookAt": {"x": 1, "y": 1, "z": 1},
        "vup": {"x": 1, "y": 1, "z": 1}
    },
    "background": {"x": 1, "y": 1, "z": 1},
    "renderConfig": {
        "imageWidth": 1,
        "imageHeight": 1,
        "samplesPerPixel": 1
    }
    
}

=== DanielPettersson/solstrale-json/tests/quad-with-non-existing-image-path.json
{
    "world": {
        "type": "quad",
        "corner": {"x": 1, "y": 1, "z": 1},
        "dirU": {"x": 1, "y": 1, "z": 1},
        "dirV": {"x": 1, "y": 1, "z": 1},
        "mat": {
            "type": "lambertian",
            "texture": {
                "type": "image",
                "path": "",
                "mirror": false
            }
        }
    },
    "camera": {
        "imageWidth": 1,
        "imageHeight": 1,
        "verticalFovDegrees": 1,
        "apertureSize": 1,
        "focusDistance": 1,
        "lookFrom": {"x": 1, "y": 1, "z": 1},
        "lookAt": {"x": 1, "y": 1, "z": 1},
        "vup": {"x": 1, "y": 1, "z": 1}
    },
    "background": {"r": 1, "g": 1, "b": 1},
    "renderConfig": {
        "imageWidth": 1,
        "imageHeight": 2,
        "samplesPerPixel": 3,
        "shader": {
            "type": "albedo"
        },
        "postProcessor": null
    }
    
}

=== DanielPettersson/solstrale-json/tests/textures.json
{
    "world": {
        "type": "hittableList",
        "list": [
            {
                "type": "sphere",
                "center": {"x": 1, "y": 1, "z": 1},
                "radius": 1,
                "mat": {
                    "type": "lambertian",
                    "texture": {
                        "type": "solidColor",
                        "color": {"x": 1, "y": 1, "z": 1}
                    }
                }
            },
            {
                "type": "sphere",
                "center": {"x": 1, "y": 1, "z": 1},
                "radius": 1,
                "mat": {
                    "type": "lambertian",
                    "texture": {
                        "type": "checker",
                        "scale": 1,
                        "odd": {
                            "type": "solidColor",
                            "color": {"x": 1, "y": 1, "z": 1}
                        },
                        "even": {
                            "type": "solidColor",
                            "color": {"x": 1, "y": 1, "z": 1}
                        }
                    }
                }
            },
            {
                "type": "sphere",
                "center": {"x": 1, "y": 1, "z": 1},
                "radius": 1,
                "mat": {
                    "type": "lambertian",
                    "texture": {
                        "type": "noise",
                        "scale": 1,
                        "color": {"x": 1, "y": 1, "z": 1}
                    }
                }
            },
            {
                "type": "sphere",
                "center": {"x": 1, "y": 1, "z": 1},
                "radius": 1,
                "mat": {
                    "type": "lambertian",
                    "texture": {
                        "type": "image",
                        "path": "tex.jpg",
                        "mirror": false
                    }
                }
            }
        ]
    },
    "camera": {
        "imageWidth": 1,
        "imageHeight": 1,
        "verticalFovDegrees": 1,
        "apertureSize": 1,
        "focusDistance": 1,
        "lookFrom": {"x": 1, "y": 1, "z": 1},
        "lookAt": {"x": 1, "y": 1, "z": 1},
        "vup": {"x": 1, "y": 1, "z": 1}
    },
    "background": {"x": 1, "y": 1, "z": 1},
    "renderConfig": {
        "imageWidth": 1,
        "imageHeight": 2,
        "samplesPerPixel": 3,
        "shader": {
            "type": "albedo"
        },
        "postProcessor": {
            "type": ""
        }
    }
    
}
